### ISSUE TITLE
[HU-N] Comparativa entre MASS Y MTD K8s

### ISSUE THREAD

**Issue by marcosrmartin** [marcosrmartin/MTD_Server#15]
Como investigador, necesito realizar una comparativa entre las implementaciones actuales de MTD a servidores web. Estas son: MASS y https://github.com/ptibom/Moving-Target-Defense-with-Kubernetes. Para así saber cual es la mejor opción para un entorno de producción.

**Comment by JJ** [comment]
Deberías siempre crear issues en función de historias de usuario. Tus historias de usuario pueden ser muy específicas y dirigidas a programadores o a gente de sistemas, pero sin historias de usuario es complicado salir adelante.

**Comment by JJ** [comment]
No puedes hacer una comparativa sin decir qué es lo que estás comparando. Y no puedes comparar a menos que formules un problema. Las historias de usuario siempre formulan problemas; comparar entre dos implementaciones tiene que ser la solución propuesta por el programador.

**Comment by marcosrmartin** [comment]
Fuera de scope
