### ISSUE TITLE
[HU-3] MTD K8s pruebas

### ISSUE THREAD

**Issue by marcosrmartin** [marcosrmartin/MTD_Server#21]
Como investigador, para llevar a cabo #15, necesito realizar pruebas con https://github.com/ptibom/Moving-Target-Defense-with-Kubernetes.

**Comment by JJ** [comment]
Una HU siempre tiene que estar en el espacio del problema. ¿Qué problema del cliente soluciona? 
Si es simplemente conseguir mayor eficiencia por el uso de Kubernetes, o más escalado, o lo que sea, sería más bien una historia de desarrollador, que se puede reformular como una HU siempre que el cliente busque hacerlo en menos tiempo.

**Comment by marcosrmartin** [comment]
Fuera de scope
