### ISSUE TITLE
La memoria tiene que poder construirse correctamente cada vez que se incorpore a main

### ISSUE THREAD

**Issue by marcosrmartin** [marcosrmartin/MTD_Server#3]
Para construir el informe necesario en #1

**Comment by JJ** [comment]
¿Qué queda por hacer aquí?

**Comment by JJ** [comment]
Tienes dos workflows que los dos usan `upload-artifact`  basado en algo relacionado con la documentación. Quizás sería más eficiente o usar diferentes jobs, o directamente en el mismo job, en diferentes pasos, si es que no es esencial que se hagan en paralelo.

**Comment by marcosrmartin** [comment]
Okey, le daré una vuelta.
