### ISSUE TITLE
[M-1] Cierre

### ISSUE THREAD

**Issue by marcosrmartin** [marcosrmartin/MTD_Server#39]
Los criterios para considerar superado el [[M-1] Infraestructura inicial MASS](https://github.com/marcosrmartin/MTD_Server/milestone/3):
* [x] https://github.com/marcosrmartin/MTD_Server/issues/19 https://github.com/marcosrmartin/MTD_Server/pull/20
* [x] https://github.com/marcosrmartin/MTD_Server/issues/17 https://github.com/marcosrmartin/MTD_Server/pull/20
* [x] https://github.com/marcosrmartin/MTD_Server/issues/18 https://github.com/marcosrmartin/MTD_Server/pull/34
* [x] https://github.com/marcosrmartin/MTD_Server/issues/33 https://github.com/marcosrmartin/MTD_Server/pull/34
* [x] https://github.com/marcosrmartin/MTD_Server/issues/38 https://github.com/marcosrmartin/MTD_Server/pull/41
* [x] https://github.com/marcosrmartin/MTD_Server/issues/40 https://github.com/marcosrmartin/MTD_Server/pull/41

**Comment by JJ** [comment]
Tendrías que intentar formular el milestone como un producto, no como un conjunto de tareas. ¿Qué tienen que probar los tests? ¿Qué tiene que parecer esta implementación inicial?
Por otro lado, sería conveniente que tagearas el repo para cada uno de los milestones, para que se vea en cada fichero en qué milestone se ha usado por última vez.
