### ISSUE TITLE
Esto debería ser parte de una historia de usuario

### ISSUE THREAD

**Issue by JJ** [marcosrmartin/MTD_Server#63]
https://github.com/marcosrmartin/MTD_Server/blob/ad371577c1cb9ba3ef446a4bf2237255ae14d3a7/doc/secciones/03_estado_del_arte.tex#L41

Precisamente lo que te he comentado va en esta dirección. El cliente es un administrador, y tiene una serie de requisitos, como este.

**Comment by marcosrmartin** [comment]
Entiendo la línea pero lo cierro al no aplicar a mi desarrollo.
