### ISSUE TITLE
Considerar el trabajo de Serrano y servidor

### ISSUE THREAD

**Issue by JJ** [marcosrmartin/MTD_Server#66]
https://github.com/marcosrmartin/MTD_Server/blob/ad371577c1cb9ba3ef446a4bf2237255ae14d3a7/doc/secciones/03_estado_del_arte.tex#L60

En nuestro caso se hacían evolucionar configuraciones que tenían un máximo de seguridad, así que esa limitación se superaba. https://ieeexplore.ieee.org/abstract/document/9185786?casa_token=IZqBB4GnmckAAAAA:NsKJ3jYKySdWPUwSLE5cFEfxH8wqCRuYnlde0ZTOY1W5Y1LszBPzBOwTLDCVgUdHzLG3maC2Sm6B

**Comment by marcosrmartin** [comment]
En el apartado 3.A donde explican los parámetros, se puede ver que se han utilizado directivas para el algoritmo como el autoindex, Content-Security-Policy y X-Frame-Options que deberian de estar siempre configuradas de forma que garantice la mayor seguridad posible. Desde mi punto de vista no tiene sentido evolucionar estos parámetros ya que sabemos cual es su configuración más segura. Pero si Erseco sacase estos parámetros del algoritmo (utilizando sus configuraciones más seguras), no tendría sentido hacer un algoritmo que puntúe según la seguridad y modificar únicamente parámetros que no la modifican. 

Decidí descartarlo por esta razón ya que si conocemos la configuración más segura, no tiene sentido evaluar otras posibles.

**Comment by marcosrmartin** [comment]
En cualquier caso lo que "critica" este punto es la base de los MTD, si se utilizan dos servidores diferentes , que rotan entre sí, aunque tengan la configuración con mayor seguridad inevitablemente tendrá mas superficie de ataque que si se usase un solo servidor. Lo mismo aplica para Erseco, si se rota entre dos configuraciones seguras habrá mas superficie de ataque que usando solo una (por ejemplo sale una vulnerabilidad para un parámetro que en la primera configuración no estaba pero al rotar es introducido).

**Comment by JJ** [comment]
@erseco, mira esto.

**Comment by erseco** [comment]
Gracias por señalar esto, @marcosrmartin  y @JJ .

Nuestro trabajo, basado en el _moving target defense_ (MTD), propone una hipótesis teórica que busca reducir el vector de ataque mediante la modificación continua de configuraciones del sistema. Es cierto que si estas configuraciones fueran vulnerables, el riesgo podría aumentar, pero es importante considerar el aspecto probabilístico de esta estrategia.

La idea central de MTD no es evitar vulnerabilidades conocidas con una única configuración segura (suponiendo que esto fuera posible), sino más bien, en hacer que el sistema sea menos predecible para el atacante al cambiar su configuración de manera rotativa. De este modo, la exposición a una vulnerabilidad en una configuración específica se ve reducida debido a la diversidad y a la rotación.

Aunque es posible que durante la rotación se introduzca una configuración vulnerable, esta no se mantendría activa el tiempo suficiente como para ser explotada de manera efectiva en la mayoría de los escenarios. Esto es lo opuesto a mantener una única configuración que, aunque segura en un momento dado, podría volverse vulnerable con el tiempo sin que el sistema ofrezca ninguna defensa dinámica.

La rotación y la diversidad inherentes al MTD, por tanto, tienen el potencial de reducir el vector de ataque al dispersar y minimizar las oportunidades de éxito de un atacante. 

Es importante recordar que, como señalan en [nuestro estudio](https://github.com/erseco/moving_target_defense) y en [trabajos previos](https://dl.acm.org/doi/10.1145/2598394.2605437), esta estrategia no es una _silver bullet_, pero proporciona una capa adicional de seguridad que complementa otras medidas defensivas, especialmente en entornos dinámicos y complejos.
