### ISSUE TITLE
Falta un capítulo de metodología

### ISSUE THREAD

**Issue by JJ** [marcosrmartin/MTD_Server#71]
Hay que explicar que metodología se usa, y esto antes de la planificación, porque esta debe salir de la metodología.

**Comment by marcosrmartin** [comment]
Esto existía, en https://github.com/marcosrmartin/MTD_Server/pull/26/commits/1269c657a5e25ebe0fecfbc01b09091723883038 fue eliminado sin querer al añadir la introducción del capítulo. Lo recupero.
